apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nri-bundle 
  namespace: newrelic
spec:
  releaseName: nri-bundle 
  chart:
    spec:
      chart: nri-bundle
      sourceRef:
        kind: HelmRepository
        name: newrelic

  interval: 5m
  install:
    remediation:
      retries: 3
      
  values:
    newrelic-infrastructure:
      # newrelic-infrastructure.enabled -- Install the [`newrelic-infrastructure` chart](https://github.com/newrelic/nri-kubernetes/tree/main/charts/newrelic-infrastructure)
      enabled: true

    nri-prometheus:
      # nri-prometheus.enabled -- Install the [`nri-prometheus` chart](https://github.com/newrelic/nri-prometheus/tree/main/charts/nri-prometheus)
      enabled: false

    nri-metadata-injection:
      # nri-metadata-injection.enabled -- Install the [`nri-metadata-injection` chart](https://github.com/newrelic/k8s-metadata-injection/tree/main/charts/nri-metadata-injection)
      enabled: true

    kube-state-metrics:
 
      enabled: false

    nri-kube-events:
      # nri-kube-events.enabled -- Install the [`nri-kube-events` chart](https://github.com/newrelic/nri-kube-events/tree/main/charts/nri-kube-events)
      enabled: false

    newrelic-logging:
      # newrelic-logging.enabled -- Install the [`newrelic-logging` chart](https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-logging)
      enabled: true


    newrelic-prometheus-agent:
      # newrelic-prometheus-agent.enabled -- Install the [`newrelic-prometheus-agent` chart](https://github.com/newrelic/newrelic-prometheus-configurator/tree/main/charts/newrelic-prometheus-agent)
      enabled: true


    global:
      # -- The cluster name for the Kubernetes cluster.
      cluster: "aks-flux-pixie"

      # -- The license key for your New Relic Account. This will be preferred configuration option if both `licenseKey` and `customSecret` are specified.
      licenseKey: ""
      # -- The license key for your New Relic Account. This will be preferred configuration option if both `insightsKey` and `customSecret` are specified.
      customSecretLicenseKey: "newrelic-key"

  